"""
Google Antigravity: Reasoning Protocols
========================================

The Holmesian method is NOT pure deduction, but a complex hybrid.
Understanding the distinction is critical to grasping how Holmes 
solves cases that baffle Scotland Yard.

DEDUCTION: General → Specific (guaranteed if premises true)
  "All men are mortal; Socrates is a man; therefore, Socrates is mortal"

INDUCTION: Specific → General (probabilistic)
  "Every swan I've seen is white; therefore, all swans are white"

ABDUCTION: Observation → Best Explanation (plausible)
  THE PRIMARY ENGINE - generating the narrative that fits the facts

"In solving a problem of this sort, the grand thing is to be able 
to reason backwards. That is a very useful accomplishment and a 
very easy one, but people do not practice it much."
- Sherlock Holmes, A Study in Scarlet
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any, Tuple, Set
from enum import Enum
from datetime import datetime
import re


# ==============================================================================
# Core Data Structures
# ==============================================================================

class ReasoningType(Enum):
    """Types of logical reasoning."""
    DEDUCTION = "deduction"
    INDUCTION = "induction"
    ABDUCTION = "abduction"
    BACKWARD = "backward"  # Reasoning from effect to cause


class CertaintyLevel(Enum):
    """Level of certainty in conclusions."""
    ABSOLUTE = "absolute"        # Deductive certainty (contingent on premises)
    PROBABILISTIC = "probabilistic"  # Inductive probability
    PLAUSIBLE = "plausible"      # Abductive best guess
    SPECULATIVE = "speculative"  # Low confidence


@dataclass
class Premise:
    """A premise in a logical argument."""
    statement: str
    is_universal: bool      # "All X are Y" vs "This X is Y"
    confidence: float       # How confident we are in this premise
    source: str            # Where this premise comes from
    evidence: List[str] = field(default_factory=list)


@dataclass
class Observation:
    """An observation that needs explanation."""
    id: str
    description: str
    context: str
    code_snippet: Optional[str] = None
    location: Optional[str] = None
    anomaly_score: float = 0.5  # How unusual is this observation


@dataclass
class Conclusion:
    """A conclusion drawn from reasoning."""
    statement: str
    reasoning_type: ReasoningType
    certainty: CertaintyLevel
    confidence: float
    premises_used: List[Premise]
    reasoning_chain: List[str]


@dataclass
class Hypothesis:
    """A hypothesis generated by abductive reasoning."""
    id: str
    explanation: str
    explains_observations: List[str]  # IDs of observations this explains
    assumptions: List[str]
    complexity_score: float  # Lower is better (Occam's Razor)
    plausibility: float
    competing_explanations: List[str] = field(default_factory=list)


@dataclass
class CausalChain:
    """A chain of cause and effect for backward reasoning."""
    effect: str
    potential_causes: List[Tuple[str, float]]  # (cause, probability)
    selected_cause: Optional[str] = None
    reasoning: str = ""


# ==============================================================================
# The Reasoning Engine
# ==============================================================================

class ReasoningEngine:
    """
    The core reasoning engine implementing multiple logical modes.
    
    Unlike pure logic systems, this engine:
    1. Tracks uncertainty and confidence
    2. Applies Occam's Razor to prefer simpler explanations
    3. Supports backward reasoning from effects to causes
    4. Generates competing hypotheses for adversarial verification
    """
    
    def __init__(self, occam_weight: float = 0.1):
        """
        Initialize the Reasoning Engine.
        
        Args:
            occam_weight: How much to penalize complex explanations
        """
        self.occam_weight = occam_weight
        
        # Knowledge bases
        self.universal_premises: List[Premise] = []
        self.observations: Dict[str, Observation] = {}
        self.conclusions: List[Conclusion] = []
        self.hypotheses: Dict[str, Hypothesis] = {}
        
        # Initialize with common security premises
        self._load_security_premises()
        
        print("[Reasoning Engine] Initialized with Holmesian reasoning modes")
    
    def _load_security_premises(self):
        """Load universal premises about smart contract security."""
        security_premises = [
            # Reentrancy
            Premise(
                statement="External calls before state updates can enable reentrancy",
                is_universal=True,
                confidence=0.95,
                source="security_canon",
                evidence=["The DAO hack", "Countless audits"]
            ),
            Premise(
                statement="If a function lacks ReentrancyGuard and makes external calls, it may be vulnerable",
                is_universal=True,
                confidence=0.85,
                source="security_canon",
                evidence=["Best practices", "OpenZeppelin recommendations"]
            ),
            
            # Oracle manipulation
            Premise(
                statement="Spot prices from AMM reserves can be manipulated with flash loans",
                is_universal=True,
                confidence=0.95,
                source="security_canon",
                evidence=["bZx hack", "Harvest Finance", "Many others"]
            ),
            
            # Access control
            Premise(
                statement="tx.origin for access control can be bypassed via phishing",
                is_universal=True,
                confidence=0.98,
                source="security_canon",
                evidence=["Solidity documentation", "Known attacks"]
            ),
            
            # Flash loans
            Premise(
                statement="Any state that can be manipulated within a transaction is flash-loan vulnerable",
                is_universal=True,
                confidence=0.90,
                source="security_canon",
                evidence=["DeFi exploits 2020-2024"]
            ),
            
            # Checks-Effects-Interactions
            Premise(
                statement="Following CEI pattern prevents most reentrancy vulnerabilities",
                is_universal=True,
                confidence=0.90,
                source="security_canon",
                evidence=["Best practices"]
            ),
        ]
        
        self.universal_premises.extend(security_premises)
        print(f"[Reasoning Engine] Loaded {len(security_premises)} universal premises")
    
    # --------------------------------------------------------------------------
    # Deductive Reasoning
    # --------------------------------------------------------------------------
    
    def deduce(
        self,
        premises: List[Premise],
        target_conclusion: Optional[str] = None
    ) -> Optional[Conclusion]:
        """
        Top-down deductive reasoning from general to specific.
        
        If the premises are true, the conclusion MUST be true.
        This gives us ABSOLUTE certainty (contingent on premises).
        
        Example:
          Premise 1: All external calls before state updates enable reentrancy
          Premise 2: This withdraw() makes an external call before state update
          Conclusion: This withdraw() enables reentrancy
        
        Args:
            premises: List of premises (universal and specific)
            target_conclusion: Optional specific conclusion to validate
        
        Returns:
            Conclusion if one can be derived, None otherwise
        """
        # Separate universal and specific premises
        universal = [p for p in premises if p.is_universal]
        specific = [p for p in premises if not p.is_universal]
        
        if not universal or not specific:
            return None
        
        # Try to form a syllogism
        for univ in universal:
            for spec in specific:
                conclusion = self._apply_syllogism(univ, spec)
                if conclusion:
                    if target_conclusion is None or target_conclusion in conclusion.statement:
                        return conclusion
        
        return None
    
    def _apply_syllogism(self, universal: Premise, specific: Premise) -> Optional[Conclusion]:
        """
        Apply syllogistic reasoning.
        
        Pattern: "All X are Y" + "This Z is X" → "This Z is Y"
        """
        # Simple pattern matching for syllogism
        # In production, this would use more sophisticated logic
        
        # Extract patterns
        all_pattern = r"(?:All|Any|Every)\s+(\w+(?:\s+\w+)*)\s+(?:are|is|can|enable|have)\s+(.+)"
        if_pattern = r"If\s+(.+?),?\s+(?:it|they)\s+(?:may be|is|are|can be)\s+(.+)"
        
        universal_match = re.match(all_pattern, universal.statement, re.IGNORECASE)
        if_match = re.match(if_pattern, universal.statement, re.IGNORECASE)
        
        if universal_match:
            subject_category = universal_match.group(1).lower()
            predicate = universal_match.group(2)
            
            # Check if specific premise matches the subject category
            if subject_category in specific.statement.lower():
                # Form conclusion
                conclusion_statement = f"{specific.statement} → {predicate}"
                
                # Calculate confidence (product of premise confidences)
                confidence = universal.confidence * specific.confidence
                
                return Conclusion(
                    statement=conclusion_statement,
                    reasoning_type=ReasoningType.DEDUCTION,
                    certainty=CertaintyLevel.ABSOLUTE,
                    confidence=confidence,
                    premises_used=[universal, specific],
                    reasoning_chain=[
                        f"Universal: {universal.statement}",
                        f"Specific: {specific.statement}",
                        f"Therefore: {conclusion_statement}"
                    ]
                )
        
        if if_match:
            condition = if_match.group(1).lower()
            result = if_match.group(2)
            
            # Check if specific premise matches the condition
            if any(word in specific.statement.lower() for word in condition.split()):
                conclusion_statement = f"This code {result}"
                confidence = universal.confidence * specific.confidence
                
                return Conclusion(
                    statement=conclusion_statement,
                    reasoning_type=ReasoningType.DEDUCTION,
                    certainty=CertaintyLevel.ABSOLUTE,
                    confidence=confidence,
                    premises_used=[universal, specific],
                    reasoning_chain=[
                        f"Rule: {universal.statement}",
                        f"Observed: {specific.statement}",
                        f"Deduced: {conclusion_statement}"
                    ]
                )
        
        return None
    
    def deduce_from_elimination(
        self,
        possibilities: List[str],
        eliminated: Set[str],
        reasoning: List[str]
    ) -> Conclusion:
        """
        "When you have eliminated the impossible, whatever remains, 
        however improbable, must be the truth."
        
        Args:
            possibilities: All possible explanations
            eliminated: Set of eliminated possibilities
            reasoning: Why each was eliminated
        
        Returns:
            Conclusion with remaining possibility
        """
        remaining = [p for p in possibilities if p not in eliminated]
        
        if len(remaining) == 1:
            return Conclusion(
                statement=remaining[0],
                reasoning_type=ReasoningType.DEDUCTION,
                certainty=CertaintyLevel.ABSOLUTE,
                confidence=0.95,  # High confidence via elimination
                premises_used=[
                    Premise(
                        statement=f"Eliminated: {e}",
                        is_universal=False,
                        confidence=0.9,
                        source="elimination"
                    )
                    for e in eliminated
                ],
                reasoning_chain=reasoning + [f"Remaining: {remaining[0]}"]
            )
        elif len(remaining) == 0:
            # All eliminated - need new possibilities
            return Conclusion(
                statement="No valid explanation found - requires new hypotheses",
                reasoning_type=ReasoningType.DEDUCTION,
                certainty=CertaintyLevel.SPECULATIVE,
                confidence=0.1,
                premises_used=[],
                reasoning_chain=reasoning + ["All possibilities eliminated"]
            )
        else:
            # Multiple remaining - need more evidence
            return Conclusion(
                statement=f"Multiple possibilities remain: {remaining}",
                reasoning_type=ReasoningType.DEDUCTION,
                certainty=CertaintyLevel.PROBABILISTIC,
                confidence=1.0 / len(remaining),
                premises_used=[],
                reasoning_chain=reasoning + [f"Remaining: {remaining}"]
            )
    
    # --------------------------------------------------------------------------
    # Inductive Reasoning
    # --------------------------------------------------------------------------
    
    def induce(
        self,
        observations: List[Observation],
        min_observations: int = 3
    ) -> Optional[Conclusion]:
        """
        Bottom-up reasoning from specific observations to general patterns.
        
        Used for building profiles from accumulated details.
        Example: Seeing scratches on phone + shaking hands + smell of alcohol
                 → User is an alcoholic
        
        This gives PROBABILISTIC certainty - the more observations,
        the more confident the generalization.
        
        Args:
            observations: List of specific observations
            min_observations: Minimum observations needed to generalize
        
        Returns:
            General pattern conclusion
        """
        if len(observations) < min_observations:
            return None
        
        # Find common themes in observations
        themes = self._extract_themes(observations)
        
        if not themes:
            return None
        
        # Form generalization from most common theme
        primary_theme = max(themes.items(), key=lambda x: x[1])
        theme_name, theme_count = primary_theme
        
        # Confidence scales with observation count
        confidence = min(0.95, 0.5 + (theme_count / len(observations)) * 0.4)
        
        return Conclusion(
            statement=f"Pattern detected: {theme_name} (observed {theme_count}/{len(observations)} times)",
            reasoning_type=ReasoningType.INDUCTION,
            certainty=CertaintyLevel.PROBABILISTIC,
            confidence=confidence,
            premises_used=[
                Premise(
                    statement=obs.description,
                    is_universal=False,
                    confidence=1 - obs.anomaly_score,
                    source="observation"
                )
                for obs in observations
            ],
            reasoning_chain=[
                f"Observed: {obs.description}" for obs in observations
            ] + [f"Generalized to: {theme_name}"]
        )
    
    def _extract_themes(self, observations: List[Observation]) -> Dict[str, int]:
        """Extract common themes from observations."""
        themes = {}
        
        # Security-specific theme detection
        theme_keywords = {
            "reentrancy": ["external call", "callback", "state after", "re-enter"],
            "oracle_risk": ["price", "oracle", "spot", "reserve", "getPrice"],
            "access_control": ["owner", "admin", "permission", "auth", "require"],
            "arithmetic": ["overflow", "underflow", "multiply", "divide"],
            "flash_loan": ["flash", "loan", "atomic", "same block"],
            "unchecked_return": ["return value", "unchecked", "ignored"],
        }
        
        for obs in observations:
            desc_lower = obs.description.lower()
            for theme, keywords in theme_keywords.items():
                if any(kw in desc_lower for kw in keywords):
                    themes[theme] = themes.get(theme, 0) + 1
        
        return themes
    
    # --------------------------------------------------------------------------
    # Abductive Reasoning (THE PRIMARY ENGINE)
    # --------------------------------------------------------------------------
    
    def abduce(
        self,
        observation: Observation,
        max_hypotheses: int = 3
    ) -> List[Hypothesis]:
        """
        Inference to the Best Explanation.
        
        THE PRIMARY ENGINE of Holmesian reasoning. Takes an observation
        (a result) and infers the most likely CAUSE that would explain it.
        
        Unlike deduction (which guarantees truth), abduction guarantees 
        only PLAUSIBILITY based on available data. It is the creative 
        leap—the formulation of a hypothesis that fits the facts better 
        than any competing hypothesis.
        
        Example:
          Observation: The victim's coat is wet but jewelry is dry
          Hypothesis A: She was caught in rain with an umbrella
          Hypothesis B: She was in a cab (coat got wet entering/exiting)
          → Select hypothesis that explains most with fewest assumptions
        
        Args:
            observation: The observation to explain
            max_hypotheses: Maximum hypotheses to generate
        
        Returns:
            List of plausible hypotheses, ranked by plausibility
        """
        self.observations[observation.id] = observation
        
        hypotheses = []
        
        # Generate hypotheses based on observation content
        hypothesis_generators = [
            self._generate_reentrancy_hypothesis,
            self._generate_oracle_hypothesis,
            self._generate_access_control_hypothesis,
            self._generate_flash_loan_hypothesis,
            self._generate_general_hypothesis,
        ]
        
        for generator in hypothesis_generators:
            hyp = generator(observation)
            if hyp and hyp.plausibility > 0.1:
                hypotheses.append(hyp)
        
        # Apply Occam's Razor - prefer simpler explanations
        for hyp in hypotheses:
            complexity_penalty = len(hyp.assumptions) * self.occam_weight
            hyp.plausibility *= (1 - complexity_penalty)
        
        # Sort by plausibility
        hypotheses.sort(key=lambda h: h.plausibility, reverse=True)
        
        # Store and return top hypotheses
        for hyp in hypotheses[:max_hypotheses]:
            self.hypotheses[hyp.id] = hyp
        
        print(f"[Abduction] Generated {len(hypotheses)} hypotheses for observation")
        
        return hypotheses[:max_hypotheses]
    
    def _generate_reentrancy_hypothesis(self, obs: Observation) -> Optional[Hypothesis]:
        """Generate reentrancy hypothesis if observation suggests it."""
        keywords = ["external call", "call", "transfer", "send", "callback", "state"]
        desc_lower = obs.description.lower()
        
        if any(kw in desc_lower for kw in keywords):
            return Hypothesis(
                id=f"hyp_reentrancy_{obs.id}",
                explanation="Reentrancy vulnerability: External call made before state update, allowing recursive calls to drain funds",
                explains_observations=[obs.id],
                assumptions=[
                    "Attacker can receive callback",
                    "State is modifiable during callback",
                    "No reentrancy guard present"
                ],
                complexity_score=3,  # 3 assumptions
                plausibility=0.7,
                competing_explanations=["Intentional callback pattern", "Read-only reentrancy"]
            )
        return None
    
    def _generate_oracle_hypothesis(self, obs: Observation) -> Optional[Hypothesis]:
        """Generate oracle manipulation hypothesis."""
        keywords = ["price", "oracle", "reserve", "getprice", "spot", "twap"]
        desc_lower = obs.description.lower()
        
        if any(kw in desc_lower for kw in keywords):
            return Hypothesis(
                id=f"hyp_oracle_{obs.id}",
                explanation="Oracle manipulation: Using manipulable price source that can be attacked with flash loan",
                explains_observations=[obs.id],
                assumptions=[
                    "Price source can be manipulated within one transaction",
                    "Flash loan liquidity is available"
                ],
                complexity_score=2,
                plausibility=0.75,
                competing_explanations=["TWAP protection", "Price bounds check"]
            )
        return None
    
    def _generate_access_control_hypothesis(self, obs: Observation) -> Optional[Hypothesis]:
        """Generate access control hypothesis."""
        keywords = ["owner", "admin", "require", "auth", "permission", "only", "tx.origin"]
        desc_lower = obs.description.lower()
        
        if any(kw in desc_lower for kw in keywords):
            return Hypothesis(
                id=f"hyp_access_{obs.id}",
                explanation="Access control vulnerability: Missing or bypassable authorization check",
                explains_observations=[obs.id],
                assumptions=[
                    "Authorization check is missing or flawed",
                    "Unauthorized user can call privileged function"
                ],
                complexity_score=2,
                plausibility=0.65,
                competing_explanations=["Intentional public access", "Check in modifier"]
            )
        return None
    
    def _generate_flash_loan_hypothesis(self, obs: Observation) -> Optional[Hypothesis]:
        """Generate flash loan attack hypothesis."""
        keywords = ["balance", "collateral", "liquidity", "stake", "deposit", "atomic"]
        desc_lower = obs.description.lower()
        
        if any(kw in desc_lower for kw in keywords):
            return Hypothesis(
                id=f"hyp_flashloan_{obs.id}",
                explanation="Flash loan attack vector: State can be manipulated atomically with borrowed capital",
                explains_observations=[obs.id],
                assumptions=[
                    "Flash loan pools exist for relevant tokens",
                    "State is readable and actionable in same transaction"
                ],
                complexity_score=2,
                plausibility=0.6,
                competing_explanations=["Cross-block check", "Minimum time lock"]
            )
        return None
    
    def _generate_general_hypothesis(self, obs: Observation) -> Optional[Hypothesis]:
        """Generate a general security hypothesis."""
        return Hypothesis(
            id=f"hyp_general_{obs.id}",
            explanation=f"Potential security issue: Anomaly detected in {obs.context}",
            explains_observations=[obs.id],
            assumptions=["Code deviates from expected pattern"],
            complexity_score=1,
            plausibility=0.3,
            competing_explanations=["Intended behavior", "False positive"]
        )
    
    def select_best_explanation(
        self,
        hypotheses: List[Hypothesis]
    ) -> Hypothesis:
        """
        Apply Occam's Razor to select the best explanation.
        
        Prefers hypotheses that:
        1. Explain all observations
        2. Require fewest assumptions
        3. Have highest plausibility
        
        Args:
            hypotheses: List of competing hypotheses
        
        Returns:
            The best hypothesis
        """
        if not hypotheses:
            raise ValueError("No hypotheses to select from")
        
        # Score each hypothesis
        def score(hyp: Hypothesis) -> float:
            observations_explained = len(hyp.explains_observations)
            complexity_penalty = hyp.complexity_score * self.occam_weight
            return hyp.plausibility * (1 + observations_explained * 0.1) * (1 - complexity_penalty)
        
        best = max(hypotheses, key=score)
        
        print(f"[Abduction] Selected best explanation: {best.explanation[:50]}...")
        
        return best
    
    # --------------------------------------------------------------------------
    # Backward Reasoning (Effect → Cause)
    # --------------------------------------------------------------------------
    
    def reason_backwards(
        self,
        effect: str,
        context: Optional[str] = None
    ) -> CausalChain:
        """
        Reason backwards from effect to cause.
        
        "In solving a problem of this sort, the grand thing is to be 
        able to reason backwards. That is a very useful accomplishment 
        and a very easy one, but people do not practice it much."
        
        Most people employ forward reasoning: given causes, predict effect.
        Holmes employs backward reasoning: given effect, find causes.
        
        This requires knowing what effects various causes produce.
        
        Args:
            effect: The observed effect (e.g., "funds drained")
            context: Additional context
        
        Returns:
            CausalChain with potential causes and their probabilities
        """
        # Known effect → cause mappings
        effect_cause_map = {
            "funds drained": [
                ("Reentrancy attack", 0.35),
                ("Flash loan + oracle manipulation", 0.25),
                ("Access control bypass", 0.20),
                ("Logic error in accounting", 0.15),
                ("Private key compromise", 0.05)
            ],
            "contract paused": [
                ("Admin action", 0.50),
                ("Automated guardian trigger", 0.25),
                ("Bug in pause logic", 0.15),
                ("Governance proposal", 0.10)
            ],
            "price manipulation": [
                ("Flash loan attack on AMM", 0.40),
                ("Whale market manipulation", 0.30),
                ("Oracle stale data", 0.20),
                ("Sandwich attack", 0.10)
            ],
            "liquidation cascade": [
                ("Flash crash / black swan", 0.30),
                ("Coordinated attack", 0.25),
                ("Oracle failure", 0.20),
                ("Protocol parameter misconfiguration", 0.15),
                ("Cross-protocol dependency failure", 0.10)
            ],
            "unexpected revert": [
                ("Out of gas", 0.25),
                ("Require statement failed", 0.25),
                ("Integer overflow/underflow", 0.15),
                ("External call failure", 0.20),
                ("Invalid state transition", 0.15)
            ],
            "storage corruption": [
                ("Storage collision in upgrade", 0.35),
                ("Delegatecall to untrusted contract", 0.30),
                ("Assembly write error", 0.20),
                ("Uninitialized storage pointer", 0.15)
            ],
        }
        
        # Find matching effect
        effect_lower = effect.lower()
        potential_causes = []
        
        for known_effect, causes in effect_cause_map.items():
            if known_effect in effect_lower or any(word in effect_lower for word in known_effect.split()):
                potential_causes.extend(causes)
        
        # If no specific match, provide general causes
        if not potential_causes:
            potential_causes = [
                ("Logic error in smart contract", 0.40),
                ("External dependency failure", 0.25),
                ("Malicious actor exploitation", 0.25),
                ("Configuration error", 0.10)
            ]
        
        # Normalize probabilities
        total = sum(p for _, p in potential_causes)
        potential_causes = [(c, p/total) for c, p in potential_causes]
        
        # Sort by probability
        potential_causes.sort(key=lambda x: x[1], reverse=True)
        
        # Select most likely cause
        selected = potential_causes[0][0] if potential_causes else None
        
        chain = CausalChain(
            effect=effect,
            potential_causes=potential_causes,
            selected_cause=selected,
            reasoning=f"Given effect '{effect}', traced backward to {len(potential_causes)} potential causes. "
                     f"Most likely: {selected} ({potential_causes[0][1]:.1%})"
        )
        
        print(f"[Backward Reasoning] Effect: {effect} → Most likely cause: {selected}")
        
        return chain
    
    def trace_causal_chain(
        self,
        final_effect: str,
        depth: int = 3
    ) -> List[CausalChain]:
        """
        Trace a full causal chain backward through multiple levels.
        
        Example:
          Effect: Contract drained
          → Cause: Reentrancy attack
          → Cause: External call before state update
          → Cause: Developer didn't follow CEI pattern
        
        Args:
            final_effect: The final observable effect
            depth: How many levels back to trace
        
        Returns:
            List of CausalChain objects, from effect to root cause
        """
        chains = []
        current_effect = final_effect
        
        for i in range(depth):
            chain = self.reason_backwards(current_effect)
            chains.append(chain)
            
            if chain.selected_cause:
                # The cause becomes the next effect to trace
                current_effect = chain.selected_cause
            else:
                break
        
        return chains
    
    # --------------------------------------------------------------------------
    # Combined Reasoning
    # --------------------------------------------------------------------------
    
    def analyze(
        self,
        code: str,
        context: str,
        known_facts: Optional[List[str]] = None
    ) -> Dict[str, Any]:
        """
        Full Holmesian analysis combining all reasoning modes.
        
        1. Create observation from code
        2. Generate abductive hypotheses
        3. Attempt deductive confirmation
        4. Build inductive patterns if multiple observations
        5. Trace backward from hypothesized effects
        
        Args:
            code: Code snippet to analyze
            context: Context about the code
            known_facts: Any known facts as premises
        
        Returns:
            Complete analysis result
        """
        # Create observation
        obs = Observation(
            id=f"obs_{len(self.observations)}",
            description=context,
            context=context,
            code_snippet=code
        )
        
        # Abductive hypotheses
        hypotheses = self.abduce(obs)
        
        # Deductive check if we have premises
        deductive_conclusions = []
        if known_facts:
            premises = [
                Premise(
                    statement=fact,
                    is_universal=False,
                    confidence=0.9,
                    source="known_fact"
                )
                for fact in known_facts
            ]
            # Add universal premises
            premises.extend(self.universal_premises)
            
            conclusion = self.deduce(premises)
            if conclusion:
                deductive_conclusions.append(conclusion)
        
        # Backward reasoning from best hypothesis
        causal_chains = []
        if hypotheses:
            best_hyp = self.select_best_explanation(hypotheses)
            chains = self.trace_causal_chain(best_hyp.explanation, depth=2)
            causal_chains = chains
        
        return {
            "observation": obs,
            "hypotheses": [
                {
                    "id": h.id,
                    "explanation": h.explanation,
                    "plausibility": h.plausibility,
                    "assumptions": h.assumptions,
                    "competing": h.competing_explanations
                }
                for h in hypotheses
            ],
            "best_explanation": hypotheses[0].explanation if hypotheses else None,
            "deductive_conclusions": [
                {
                    "statement": c.statement,
                    "confidence": c.confidence,
                    "reasoning": c.reasoning_chain
                }
                for c in deductive_conclusions
            ],
            "causal_chain": [
                {
                    "effect": chain.effect,
                    "likely_cause": chain.selected_cause,
                    "probability": chain.potential_causes[0][1] if chain.potential_causes else 0
                }
                for chain in causal_chains
            ]
        }


# ==============================================================================
# CLI Interface
# ==============================================================================

if __name__ == "__main__":
    import argparse
    import json
    
    parser = argparse.ArgumentParser(description="Reasoning Engine - Holmesian Logic")
    parser.add_argument("--mode", choices=["abduce", "deduce", "backward", "full"], default="abduce")
    parser.add_argument("--observation", type=str, help="Observation to analyze")
    parser.add_argument("--effect", type=str, help="Effect for backward reasoning")
    args = parser.parse_args()
    
    engine = ReasoningEngine()
    
    # Demo observation
    demo_obs = Observation(
        id="demo_1",
        description="Function makes external call via .call() before updating user balance",
        context="withdraw() function in Bank.sol",
        code_snippet="(bool success,) = msg.sender.call{value: amount}(\"\"); balances[msg.sender] -= amount;"
    )
    
    if args.mode == "abduce":
        hypotheses = engine.abduce(demo_obs)
        print("\nAbductive Hypotheses:")
        for h in hypotheses:
            print(f"  [{h.plausibility:.2f}] {h.explanation}")
            print(f"       Assumptions: {h.assumptions}")
    
    elif args.mode == "backward":
        effect = args.effect or "funds drained from protocol"
        chain = engine.reason_backwards(effect)
        print(f"\nBackward Reasoning from: {effect}")
        print("Potential Causes:")
        for cause, prob in chain.potential_causes:
            print(f"  [{prob:.1%}] {cause}")
    
    elif args.mode == "full":
        result = engine.analyze(
            code=demo_obs.code_snippet,
            context=demo_obs.context,
            known_facts=["This contract handles user deposits", "No reentrancy guard modifier observed"]
        )
        print(json.dumps(result, indent=2, default=str))
